### ISSUE TITLE
Slim.js

### ISSUE THREAD

**Issue by eavichay** [gothinkster/realworld#215]
repo: https://github.com/eavichay/slimjs-realworld-example-app

**Comment by eavichay** [comment]
ping?

**Comment by anishkny** [comment]
hey @eavichay thanks for putting this together. Could you clean up the README to better align with the one [here](https://github.com/gothinkster/realworld-starter-kit)? Thanks!

**Comment by eavichay** [comment]
@anishkny Done.

**Comment by anishkny** [comment]
I am getting this error for `npm run build`/`npm run start`. I would suggest getting this project building on TravisCI/CircleCI/Azure Pipelines as reference.

```
$ npm run start

> slimjs-client-boilerplate@1.0.1 start /tmp/slimjs-realworld-example-app
> webpack-dev-server --profile --watch --progress --colors --config webpack.config.js

/tmp/slimjs-realworld-example-app/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/tmp/slimjs-realworld-example-app/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/tmp/slimjs-realworld-example-app/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
