### ISSUE TITLE
Hyperapp

### ISSUE THREAD

**Issue by kwasniew** [gothinkster/realworld#257]
Frontend in Hyperapp.

Status: finished

Codebase: https://github.com/kwasniew/hyperapp-realworld-example-app

Demo: https://hyperapp.netlify.com/

**Comment by anishkny** [comment]
good work @kwasniew !! 🎉 

It may be worth it to turn on TravisCI build/test for this repo.

I am seeing this weird bug in my feed when trying locally: 
<img width="309" alt="screen shot 2018-10-03 at 8 03 38 pm" src="https://user-images.githubusercontent.com/357499/46445988-ad5da100-c747-11e8-9a33-60474889aad3.png">

Also, when I ran `npm test` locally, I get:
```

  ● global feed

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "global feed 1".

    - Snapshot
    + Received

    @@ -152,11 +152,11 @@
                    <div class="article-meta">
                      <a href="/profile/drc">
                        <img src="https://static.productionready.io/images/smiley-cyrus.jpg" alt="drc">
                      </a>
                      <div class="info">
    -                   <a class="author" href="/profile/drc">drc</a><span class="date">Wed Jul 11 2018</span></div>
    +                   <a class="author" href="/profile/drc">drc</a><span class="date">Tue Jul 10 2018</span></div>
                      <button class="btn btn-sm btn-outline-primary pull-xs-right">
                        <i class="ion-heart"></i> 1</button>
                    </div>
                    <a href="/article/article-new-q8efhz" class="preview-link">
                      <h1>Article New</h1>
    @@ -172,11 +172,11 @@
                    <div class="article-meta">
                      <a href="/profile/kolibreath">
                        <img src="https://static.productionready.io/images/smiley-cyrus.jpg" alt="kolibreath">
                      </a>
                      <div class="info">
    -                   <a class="author" href="/profile/kolibreath">kolibreath</a><span class="date">Wed Jul 11 2018</span></div>
    +                   <a class="author" href="/profile/kolibreath">kolibreath</a><span class="date">Tue Jul 10 2018</span></div>
                      <button class="btn btn-sm btn-outline-primary pull-xs-right">
                        <i class="ion-heart"></i> 1</button>
                    </div>
                    <a href="/article/testing-d0nqzg" class="preview-link">
                      <h1>Testing</h1>
    @@ -188,11 +188,11 @@
                    <div class="article-meta">
                      <a href="/profile/qaudaffyazmi">
                        <img src="https://static.productionready.io/images/smiley-cyrus.jpg" alt="qaudaffyazmi">
                      </a>
                      <div class="info">
    -                   <a class="author" href="/profile/qaudaffyazmi">qaudaffyazmi</a><span class="date">Wed Jul 11 2018</span></div>
    +                   <a class="author" href="/profile/qaudaffyazmi">qaudaffyazmi</a><span class="date">Tue Jul 10 2018</span></div>
                      <button class="btn btn-sm btn-outline-primary pull-xs-right">
                        <i class="ion-heart"></i> 1</button>
                    </div>
                    <a href="/article/erwr-zw7p09" class="preview-link">
                      <h1>erwr</h1>

      77 |       expect(element(TAG)()).toBeInTheDocument();
      78 |     });
    > 79 |     expect(pretty(document.body.innerHTML)).toMatchSnapshot();
         |                                             ^
      80 |   });
      81 | });
      82 |

      at toMatchSnapshot (test/component/approval.test.js:79:45)

  ● tag feed

    expect(value).toMatchSnapshot()

    Received value does not match stored snapshot "tag feed 1".

    - Snapshot
    + Received

    @@ -240,11 +240,11 @@
                    <div class="article-meta">
                      <a href="/profile/huult">
                        <img src="https://static.productionready.io/images/smiley-cyrus.jpg" alt="huult">
                      </a>
                      <div class="info">
    -                   <a class="author" href="/profile/huult">huult</a><span class="date">Thu May 10 2018</span></div>
    +                   <a class="author" href="/profile/huult">huult</a><span class="date">Wed May 09 2018</span></div>
                      <button class="btn btn-sm btn-outline-primary pull-xs-right">
                        <i class="ion-heart"></i> 18</button>
                    </div>
                    <a href="/article/abcd-4goken" class="preview-link">
                      <h1>abcd</h1>

      120 |       expect(elements(TAGGED_PREVIEW, "sushi")()).toHaveLength(10)
      121 |     );
    > 122 |     expect(pretty(document.body.innerHTML)).toMatchSnapshot();
          |                                             ^
      123 |   });
      124 | });
      125 |

      at toMatchSnapshot (test/component/approval.test.js:122:45)

 › 2 snapshots failed.
Snapshot Summary
 › 2 snapshots failed from 1 test suite.
```
